### ISSUE TITLE
[MULI-23] Language Support for Russian

### ISSUE THREAD

**Issue by tom-reith** [sw21-tug/Team_29#33]
**User Story**
I as a user
Want to use the app in Russian
So that I can enter the Russian market with my product

**Acceptance Criteria**
Scenario 1: Changing the Application Text to Russian
GIVEN a user has started the app
AND the app is in English
WHEN navigating to the settings
AND navigating to "language"
AND navigating to "Russian"
THEN all texts in the app are in Russian (except for the user entered input)

Scenario 2: Changing the Application Text to English
GIVEN a user has started the app
AND the app is in Russian
WHEN navigating to the settings
AND navigating to "language"
AND navigating to "English"
THEN all texts in the app are in English (except for the user entered input)

**Technical Specification**

- [ ] per default the app is in english
- [ ] the solution should be extendable to work with further developments
check: https://developer.android.com/training/basics/supporting-devices/languages

**Texts Translations**
Games = Игры
Statistics = Статистика
History = История
Tips = Подсказки
Options = Опции
This is xxx Fragment = Это ххх фрагмент
Start New Game = Начать новую Игру
Enter Player Names = Впиши имена игроков
Player <> = Игрок <>
Heart Round = Раунд Черви
Underdog = Проигравший
End Game = Конец игры
Create User = Создай пользователя
Please Enter Your Username = Пожалуйста, введите ваш ник пользователя

**Mockups**
Mockup of the options menu:
<img width="282" alt="Screenshot 2021-04-28 at 10 28 28" src="https://user-images.githubusercontent.com/70277903/116372297-918ddf00-a80c-11eb-86ec-1e9af14e162c.png">

Mockup of the language chooser:
<img width="283" alt="Screenshot 2021-04-28 at 10 28 21" src="https://user-images.githubusercontent.com/70277903/116372318-95216600-a80c-11eb-8a0e-a7ea5127a2f0.png">

**Comment by VladB66** [comment]
Options = Настройки, Enter Player Names = Введите имена игроков, Create User = Создать пользователя, Please Enter Your Username = Пожалуйста, введите Ваше имя пользователя

**Comment by tom-reith** [comment]
another link which the team wanted to share: https://protocoderspoint.com/how-to-change-whole-app-language-in-android-programmatically/#Step_2_-_Create_a_new_stringsxml_with_locale
